server:
  servlet:
    context-path: /gerenciamento-funcionarios/api

spring:
  application:
    name: gerenciamento-funcionarios

springdoc:
  swagger-ui:
    enabled: true
    path: /public/swagger
  api-docs:
    enabled: true